services:

  axon-server:
    image: axoniq/axonserver:latest
    container_name: axonserver
    ports:
      - "8024:8024"   # HTTP dashboard
      - "8124:8124"   # gRPC communication (Axon clients)
    environment:
      - AXONIQ_AXONSERVER_DEVMODE_ENABLED=true

  mongodb:
    image: "mongo:6-jammy"
    ports:
      - '27017:27017'
    restart: always

  postgresql:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=default
      - POSTGRES_DB=bank_db
    ports:
      - "5432:5432"
    restart: always