server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/user

axon:
  serializer:
    general: jackson        # Serializer for events, tokens, etc.
    events: jackson
    messages: jackson

  eventhandling:
    processors:
      user-group:
        mode: tracking      # Using TrackingEventProcessor
        source: eventStore
        initial-segment-count: 1
        thread-count: 1

  axonserver:
    enabled: true
    servers: 127.0.0.1:8124
    devmode-enabled: true